env_files:
  github_token: ~/.config/goreleaser/github_token

before:
  hooks:
    - go mod download
builds:
  -
    id: "docker-debug"
    main: ./main.go
    goos:
      - darwin
    goarch:
      - amd64

archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

brews:
  -
    name: drydock

    tap:
      owner: sandstorm
      name: homebrew-tap

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: Sandstorm Release Bot
      email: release-bot@sandstorm.de

    # Folder inside the repository to put the formula.
    # Default is the root folder.
    folder: Formula

    # Your app's homepage.
    # Default is empty.
    homepage: "https://github.com/sandstorm/drydock"

    # Your app's description.
    # Default is empty.
    description: "Drydock - Docker Debug Tools"

    custom_block: |
      def caveats
        caveats =
          <<~EOS

            You can use "drydock" as standalone executable. If you find it more convenient as docker subcommands (i.e.
            "docker execroot" instead of "drydock execroot", you can run the following commands to set up
            docker plugin symlinks:

            ---------------------------------------------------------------------------------
            mkdir -p ~/.docker/cli-plugins
            rm -f ~/.docker/cli-plugins/docker-execroot
            ln -s #{pkgshare}/drydock ~/.docker/cli-plugins/docker-execroot

            rm -f ~/.docker/cli-plugins/docker-vscode
            ln -s #{pkgshare}/drydock ~/.docker/cli-plugins/docker-vscode
      
            rm -f ~/.docker/cli-plugins/docker-phpprofiler
            ln -s #{pkgshare}/drydock ~/.docker/cli-plugins/docker-phpprofiler

            rm -f ~/.docker/cli-plugins/docker-xdebug
            ln -s #{pkgshare}/drydock ~/.docker/cli-plugins/docker-xdebug
            ---------------------------------------------------------------------------------
          EOS

        caveats
      end

    install: |
      pkgshare.install Dir["*"]
