env_files:
  github_token: ~/.config/goreleaser/github_token

project_name: drydock
release:
  github:
    owner: sandstorm
    name: drydock
  name_template: '{{.Tag}}'

before:
  hooks:
    - go mod download
builds:
  -
    id: "drydock"
    main: ./main.go
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
- name_template: >-
    {{- .ProjectName }}_
    {{- title .Os }}_
    {{- if eq .Arch "amd64" }}x86_64
    {{- else if eq .Arch "386" }}i386
    {{- else }}{{ .Arch }}{{ end }}
    {{- if .Arm }}v{{ .Arm }}{{ end -}}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

brews:
  -
    name: drydock

    repository:
      owner: sandstorm
      name: homebrew-tap

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: Sandstorm Release Bot
      email: release-bot@sandstorm.de

    # Folder inside the repository to put the formula.
    # Default is the root folder.
    folder: Formula

    # Your app's homepage.
    # Default is empty.
    homepage: "https://github.com/sandstorm/drydock"

    # Your app's description.
    # Default is empty.
    description: "Drydock - Docker Debug Tools"

    install: |
      libexec.install Dir["*"]
      bin.write_exec_script libexec/"drydock"
