env_files:
  github_token: ~/.config/goreleaser/github_token

before:
  hooks:
    - go mod download
builds:
  -
    id: "docker-debug"
    main: ./main.go
    goos:
      - darwin
    goarch:
      - amd64

archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

brews:
  -
    name: docker-execroot

    tap:
      owner: sandstorm
      name: homebrew-tap

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: Sandstorm Release Bot
      email: release-bot@sandstorm.de

    # Folder inside the repository to put the formula.
    # Default is the root folder.
    folder: Formula

    # Your app's homepage.
    # Default is empty.
    homepage: "https://github.com/sandstorm/docker-execroot"

    # Your app's description.
    # Default is empty.
    description: "Sandstorm Docker Debug Tools"

    custom_block: |
      def caveats
        caveats =
          <<~EOS

            !!! Please run the following commands to finish installing the docker-execroot plugin:

            ---------------------------------------------------------------------------------
            mkdir -p ~/.docker/cli-plugins
            rm -f ~/.docker/cli-plugins/docker-execroot
            ln -s #{pkgshare}/docker-execroot ~/.docker/cli-plugins/docker-execroot

            rm -f ~/.docker/cli-plugins/docker-vscode
            ln -s #{pkgshare}/docker-execroot ~/.docker/cli-plugins/docker-vscode
      
            rm -f ~/.docker/cli-plugins/docker-phpprofiler
            ln -s #{pkgshare}/docker-execroot ~/.docker/cli-plugins/docker-phpprofiler
            ---------------------------------------------------------------------------------
          EOS

        caveats
      end

    install: |
      pkgshare.install Dir["*"]
